# Generated by Django 2.1.2 on 2018-11-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0003_emailconfirmationattempt_passwordresetattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
