# Generated by Django 2.1.3 on 2018-11-08 05:56

import arkav_is_api.arkavauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0005_refactor_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetconfirmationattempt',
            name='token',
            field=models.CharField(default=arkav_is_api.arkavauth.models.generate_email_confirmation_token, max_length=30, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='registrationconfirmationattempt',
            name='token',
            field=models.CharField(default=arkav_is_api.arkavauth.models.generate_email_confirmation_token, max_length=30, null=True, unique=False),
        ),
    ]
