# Generated by Django 2.1.3 on 2018-11-08 05:56

from string import ascii_letters, digits
import arkav_is_api.arkavauth.models
from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_email_confirmation_token(length=30):
    return get_random_string(length, allowed_chars=ascii_letters + digits)


def fill_registration_confirmation_token(apps, schema_editor):
    RegistrationConfirmationAttempt = apps.get_model('arkavauth', 'RegistrationConfirmationAttempt')
    for attempt in RegistrationConfirmationAttempt.objects.all():
        attempt.token = generate_email_confirmation_token()
        attempt.save()


def fill_password_reset_confirmation_token(apps, schema_editor):
    PasswordResetConfirmationAttempt = apps.get_model('arkavauth', 'PasswordResetConfirmationAttempt')
    for attempt in PasswordResetConfirmationAttempt.objects.all():
        attempt.token = generate_email_confirmation_token()
        attempt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0006_add_unique_constraint_to_tokens_1'),
    ]

    operations = [
        migrations.RunPython(fill_registration_confirmation_token),
        migrations.RunPython(fill_password_reset_confirmation_token),
    ]
