# Generated by Django 2.1.3 on 2018-11-09 12:14

from django.db import migrations


def lowercase_all_emails(apps, schema_editor):
    User = apps.get_model('arkavauth', 'User')
    for user in User.objects.all():
        lowercased_email = user.email.lower()
        if user.email != lowercased_email:
            user.email = lowercased_email
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('arkavauth', '0008_add_unique_constraint_to_tokens_3'),
    ]

    operations = [
        migrations.RunPython(lowercase_all_emails),
    ]
