# Generated by Django 2.1.4 on 2018-12-30 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_open', models.BooleanField(default=False)),
                ('session_one_normal_price', models.IntegerField()),
                ('session_two_price', models.IntegerField()),
                ('session_one_discounted_price', models.IntegerField()),
                ('session_one_max_capacity', models.IntegerField()),
                ('session_one_current_capacity', models.IntegerField()),
                ('session_two_max_capacity', models.IntegerField()),
                ('session_two_current_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('is_register_session_one', models.BooleanField()),
                ('is_register_session_two', models.BooleanField()),
                ('is_using_student_discount', models.BooleanField()),
                ('student_card', models.CharField(max_length=128, null=True)),
                ('payment_receipt', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
