# Generated by Django 2.1.4 on 2019-01-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='student_card',
        ),
        migrations.AddField(
            model_name='ticket',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seminar.Registrant'),
        ),
    ]
