# Generated by Django 2.1.4 on 2019-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_auto_20190118_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Menunggu Pembayaran'), (2, 'Sukses'), (-1, 'Dibatalkan')]),
        ),
    ]
