# Generated by Django 2.1.4 on 2019-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_auto_20190118_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='payment_receipt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
