# Generated by Django 2.1.4 on 2019-01-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_auto_20190118_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='status',
            field=models.IntegerField(choices=[(0, 'Menunggu Pembayaran'), (1, 'Menunggu Validasi'), (2, 'Sukses'), (3, 'Dibatalkan')], default=0),
        ),
    ]
