# Generated by Django 2.1.5 on 2019-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_auto_20190122_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mail_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
