# Generated by Django 2.1.5 on 2019-01-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0009_auto_20190124_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='registrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seminar.Registrant'),
        ),
    ]
