# Generated by Django 2.1.5 on 2019-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0011_registrant_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
