# Generated by Django 2.1.3 on 2018-12-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='questionselection',
            name='is_corect',
            field=models.BooleanField(default=False),
        ),
    ]
