# Generated by Django 2.1.3 on 2018-12-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20181205_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionselection',
            old_name='is_corect',
            new_name='is_correct',
        ),
    ]
