# Generated by Django 2.1.4 on 2018-12-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20181208_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.QuizAttempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Question')),
            ],
        ),
    ]
