# Generated by Django 2.1.4 on 2018-12-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20181208_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizAttempt'),
        ),
    ]
