# Generated by Django 2.1.4 on 2018-12-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181208_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptanswer',
            name='answer',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1, null=True),
        ),
    ]
