# Generated by Django 2.1.4 on 2018-12-08 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20181209_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
