# Generated by Django 2.1.4 on 2018-12-08 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_question_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
