# Generated by Django 2.1.4 on 2018-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20181214_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionselection',
            name='value',
            field=models.TextField(),
        ),
    ]
