# Generated by Django 2.1.2 on 2018-11-04 15:02

import arkav_is_api.uploader.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file', models.FileField(upload_to=arkav_is_api.uploader.models.generate_upload_to_path)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
