# Generated by Django 2.1.3 on 2018-11-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
