# Generated by Django 2.1.3 on 2018-11-08 15:59

from django.db import migrations


def remove_upload_path_prefix(apps, schema_editor):
    UploadedFile = apps.get_model('uploader', 'UploadedFile')
    prefix_to_remove = 'uploads/'
    for uploaded_file in UploadedFile.objects.all():
        if uploaded_file.file.name.startswith(prefix_to_remove):
            uploaded_file.file.name = uploaded_file.file.name[len(prefix_to_remove):]
            uploaded_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_uploadedfile_content_type'),
    ]

    operations = [
        migrations.RunPython(remove_upload_path_prefix),
    ]
