# Generated by Django 2.1.1 on 2018-09-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_team_members', models.IntegerField(default=1)),
                ('is_registration_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competition.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('widget_parameters', models.TextField()),
                ('requires_validation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'task categories',
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('awaiting_validation', 'Awaiting validation'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_responses', to='competition.Task')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TaskWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('secret_code', models.CharField(max_length=20)),
                ('is_participating', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_teams', to='competition.Stage')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='competition.Competition')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='competition.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='competition.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_responses', to='competition.Team'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='competition.TaskCategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='competition.Stage'),
        ),
        migrations.AddField(
            model_name='task',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='competition.TaskWidget'),
        ),
        migrations.AlterUniqueTogether(
            name='taskresponse',
            unique_together={('task', 'team')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='stage',
            order_with_respect_to='competition',
        ),
    ]
