# Generated by Django 2.1.1 on 2018-09-28 04:25

import arkav_is_api.competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_add_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['competition', 'order']},
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='stage',
            order_with_respect_to=None,
        ),
    ]
