# Generated by Django 2.1.1 on 2018-09-28 04:26

import arkav_is_api.competition.models
from django.db import migrations, models
from string import ascii_uppercase, digits
from django.utils.crypto import get_random_string


def generate_team_secret_code():
    return get_random_string(length=6, allowed_chars=ascii_uppercase + digits)


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_manual_stage_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='secret_code',
            field=models.CharField(default=generate_team_secret_code, max_length=20, unique=True),
        ),
    ]
