# Generated by Django 2.1.1 on 2018-09-29 16:46

import arkav_is_api.competition.models
from django.db import migrations, models
from string import ascii_letters
from django.utils.crypto import get_random_string


def generate_random_str(length=30):
    return get_random_string(length, allowed_chars=ascii_letters)


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_add_team_member_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=generate_random_str, max_length=30)),
                ('filename', models.CharField(max_length=30)),
            ],
        ),
    ]
