# Generated by Django 2.1.1 on 2018-09-29 14:48

import arkav_is_api.competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_add_team_member_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=arkav_is_api.competition.models.generate_random_str, max_length=30)),
            ],
        ),
    ]
