# Generated by Django 2.1.1 on 2018-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
