# Generated by Django 2.1.1 on 2018-10-01 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresponse',
            name='created_at',
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='last_submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
