# Generated by Django 2.1.2 on 2018-10-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_team_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='view_icon',
            field=models.URLField(default=''),
        ),
    ]
