# Generated by Django 2.1.2 on 2018-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_competition_view_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='min_team_members',
            field=models.IntegerField(default=1),
        ),
    ]
