# Generated by Django 2.1.2 on 2018-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_competitioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='categories',
            field=models.ManyToManyField(to='competition.CompetitionCategory'),
        ),
    ]
