# Generated by Django 2.1.2 on 2018-11-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competition_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
