# Generated by Django 2.1.2 on 2018-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_auto_20181104_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(max_length=50),
        ),
    ]
