# Generated by Django 2.1.3 on 2018-11-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_auto_20181104_0521'),
        ('competition', '0012_move_file_to_uploader'),
    ]

    operations = [
    ]
