# Generated by Django 2.1.2 on 2018-11-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='content_type',
        ),
    ]
