# Generated by Django 2.1.3 on 2018-11-08 09:31

import arkav_is_api.competition.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_merge_20181105_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='school',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='team',
            name='secret_code',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='team',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='competition.CompetitionCategory'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_full_name',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_token',
            field=models.CharField(default=arkav_is_api.competition.models.generate_team_invitation_token, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='taskresponse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_responses', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
