# Generated by Django 2.1.3 on 2018-11-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_refactor_competition_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='competition.CompetitionCategory'),
        ),
    ]
