# Generated by Django 2.1.3 on 2018-11-09 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_refactor_competition_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
