# Generated by Django 2.1.4 on 2018-12-08 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingClassParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('domicile', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'QUIZ_ATTEMPTED'), (3, 'QUIZ_FINISHED'), (4, 'ACCEPTED'), (5, 'REJECTED')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
