# Generated by Django 2.1.4 on 2018-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingclassparticipant',
            name='quiz_attempt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
