# Generated by Django 2.1.4 on 2018-12-08 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preevent', '0003_auto_20181209_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingclassparticipant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
