# Generated by Django 2.1.4 on 2018-12-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preevent', '0004_auto_20181209_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coding_class_registration_open', models.BooleanField(default=False)),
                ('coding_class_quiz_slug', models.SlugField()),
            ],
        ),
    ]
