# Generated by Django 2.1.4 on 2018-12-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preevent', '0005_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingclassparticipant',
            name='student_card',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codingclassparticipant',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'QUIZ ATTEMPTED'), (3, 'QUIZ FINISHED'), (4, 'ACCEPTED'), (5, 'REJECTED')]),
        ),
    ]
