# Generated by Django 2.1.4 on 2018-12-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preevent', '0006_auto_20181214_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingclassparticipant',
            name='student_card',
            field=models.UUIDField(),
        ),
    ]
